# Generated by Django 6.0.1 on 2026-01-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionHourlyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=5)),
                ('datetime', models.DateTimeField()),
                ('load_mw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StateDailyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('energy_mu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('load_mw', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('state', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('temperature_c', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('state', 'datetime'), name='unique_state_datetime_weather')],
            },
        ),
    ]
