# Generated by Django 6.0.1 on 2026-01-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateLoad5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('load_mw', models.FloatField()),
            ],
            options={
                'ordering': ['-datetime'],
                'constraints': [models.UniqueConstraint(fields=('state', 'datetime'), name='unique_state_datetime_5min_load')],
            },
        ),
    ]
